"""Pydantic schemas for MCP Server."""

from mcp.schemas.base import (
    AgentManifest,
    BaseRequest,
    BaseResponse,
    ErrorResponse,
    RequestContext,
    ToolExecutionRequest,
    ToolExecutionResponse,
)
from mcp.schemas.integrations import (
    # Enums
    ArrearsStatus,
    ContactType,
    DriveMimeType,
    GmailLabelType,
    PropertyClass,
    PropertyStatus,
    RentFrequency,
    # Gmail schemas
    EmailSummary,
    GmailMessage,
    GmailThread,
    MessageHeader,
    MessagePayload,
    SendEmailResult,
    ThreadSummary,
    # Google Drive schemas
    DocumentContent,
    DocumentInfo,
    DriveFile,
    DrivePermission,
    DriveUser,
    ExpiryAlert,
    # VaultRE schemas
    Agent,
    OpenHome,
    OpenHomeSummary,
    PriceInfo,
    PropertyAddress,
    PropertyContacts,
    PropertyFeedback,
    PropertyPhoto,
    PropertySummary,
    VaultREContact,
    VaultREProperty,
    # Ailo schemas
    AiloLedger,
    AiloTenant,
    ArrearsReport,
    CommunicationEntry,
    CommunicationHistory,
    LedgerSummary,
    PaymentEntry,
    # Unified schemas
    AiloCollectionResult,
    ComplianceAlert,
    DriveCollectionResult,
    GmailCollectionResult,
    UnifiedPropertyData,
    VaultRECollectionResult,
    # Tool input/output schemas
    CheckDocumentExpiryInput,
    CheckDocumentExpiryOutput,
    FetchPropertyEmailsInput,
    FetchPropertyEmailsOutput,
    GetDocumentContentInput,
    GetDocumentContentOutput,
    GetPropertyContactsInput,
    GetPropertyContactsOutput,
    GetTenantCommunicationHistoryInput,
    GetTenantCommunicationHistoryOutput,
    GetUpcomingOpenHomesInput,
    GetUpcomingOpenHomesOutput,
    ListActivePropertiesInput,
    ListActivePropertiesOutput,
    ListArrearsTenanciesInput,
    ListArrearsTenanciesOutput,
    ListPropertyDocumentsInput,
    ListPropertyDocumentsOutput,
    SearchCommunicationThreadsInput,
    SearchCommunicationThreadsOutput,
    UnifiedDataCollectionInput,
    UnifiedDataCollectionOutput,
)
from mcp.schemas.tools import (
    AnalyzeFeedbackInput,
    AnalyzeFeedbackOutput,
    CalculateBreachInput,
    CalculateBreachOutput,
    ExtractExpiryInput,
    ExtractExpiryOutput,
    GenerateVendorReportInput,
    GenerateVendorReportOutput,
    OCRDocumentInput,
    OCRDocumentOutput,
    PrepareBreachNoticeInput,
    PrepareBreachNoticeOutput,
)
from mcp.schemas.versioning import VersionedSchema

__all__ = [
    # Base schemas
    "BaseRequest",
    "BaseResponse",
    "ErrorResponse",
    "RequestContext",
    "ToolExecutionRequest",
    "ToolExecutionResponse",
    "AgentManifest",
    "VersionedSchema",
    # Existing tool schemas
    "AnalyzeFeedbackInput",
    "AnalyzeFeedbackOutput",
    "CalculateBreachInput",
    "CalculateBreachOutput",
    "ExtractExpiryInput",
    "ExtractExpiryOutput",
    "GenerateVendorReportInput",
    "GenerateVendorReportOutput",
    "OCRDocumentInput",
    "OCRDocumentOutput",
    "PrepareBreachNoticeInput",
    "PrepareBreachNoticeOutput",
    # Integration enums
    "ArrearsStatus",
    "ContactType",
    "DriveMimeType",
    "GmailLabelType",
    "PropertyClass",
    "PropertyStatus",
    "RentFrequency",
    # Gmail schemas
    "EmailSummary",
    "GmailMessage",
    "GmailThread",
    "MessageHeader",
    "MessagePayload",
    "SendEmailResult",
    "ThreadSummary",
    # Google Drive schemas
    "DocumentContent",
    "DocumentInfo",
    "DriveFile",
    "DrivePermission",
    "DriveUser",
    "ExpiryAlert",
    # VaultRE schemas
    "Agent",
    "OpenHome",
    "OpenHomeSummary",
    "PriceInfo",
    "PropertyAddress",
    "PropertyContacts",
    "PropertyFeedback",
    "PropertyPhoto",
    "PropertySummary",
    "VaultREContact",
    "VaultREProperty",
    # Ailo schemas
    "AiloLedger",
    "AiloTenant",
    "ArrearsReport",
    "CommunicationEntry",
    "CommunicationHistory",
    "LedgerSummary",
    "PaymentEntry",
    # Unified schemas
    "AiloCollectionResult",
    "ComplianceAlert",
    "DriveCollectionResult",
    "GmailCollectionResult",
    "UnifiedPropertyData",
    "VaultRECollectionResult",
    # Integration tool input/output schemas
    "CheckDocumentExpiryInput",
    "CheckDocumentExpiryOutput",
    "FetchPropertyEmailsInput",
    "FetchPropertyEmailsOutput",
    "GetDocumentContentInput",
    "GetDocumentContentOutput",
    "GetPropertyContactsInput",
    "GetPropertyContactsOutput",
    "GetTenantCommunicationHistoryInput",
    "GetTenantCommunicationHistoryOutput",
    "GetUpcomingOpenHomesInput",
    "GetUpcomingOpenHomesOutput",
    "ListActivePropertiesInput",
    "ListActivePropertiesOutput",
    "ListArrearsTenanciesInput",
    "ListArrearsTenanciesOutput",
    "ListPropertyDocumentsInput",
    "ListPropertyDocumentsOutput",
    "SearchCommunicationThreadsInput",
    "SearchCommunicationThreadsOutput",
    "UnifiedDataCollectionInput",
    "UnifiedDataCollectionOutput",
]
